[package]
name = "bounded"
version.workspace = true
edition.workspace = true

[dependencies]
fly = { path = "../fly" }
solver = { path = "../solver" }

itertools = "0.10.5"
thiserror = "1.0.40"
biodivine-lib-bdd = "0.5.1"
cadical = "0.1.14"
fxhash = "0.2.1"
bitvec = "1.0.1"
log = "0.4.19"
