[package]
name = "formats"
version.workspace = true
edition.workspace = true

[dependencies]
fly = { path = "../fly" }
smtlib = { path = "../smtlib" }
solver = { path = "../solver" }

itertools = "0.10.5"
petgraph = "0.6.5"
regex = "1.11.1"
