#!/bin/sh

## Copy this script to .git/hooks/prepare-commit-msg to automatically add the
##`Signed-off-by` line required by the DCO (see https://cla.vmware.com/dco).

NAME=$(git config user.name)
EMAIL=$(git config user.email)

if [ -z "$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi

if [ -z "$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: $NAME <$EMAIL>" \
    --in-place "$1"
